#encoding: utf-8

module EasyIconsHelper

  EASY_ICONS = {
      'icon-dashboard'       => '\F056E',
      'icon-remove'          => '\F0375',
      'icon-del'             => '\F01B4',
      'icon-delete'          => '\F01B4',
      'icon-user'            => '\F0004',
      'icon-group'           => '\F02C3',
      'icon-time-add'        => '\F0024',
      'icon-timer'           => '\F13AB',
      'icon-reload'          => '\F0453',
      'icon-issue-update'    => '\F014E',
      'icon-lock'            => '\F033E',
      'icon-split'           => '\F0AB6',
      'icon-unlock'          => '\F0340',
      'icon-details'         => '\F01C6',
      'icon-zoom-in'         => '\F06ED',
      'icon-zoom-out'        => '\F06EC',
      'icon-magnifier'       => '\F0349',
      'icon-templates'       => '\F0645',
      'icon-list'            => '\F0279',
      'icon-slab'            => '\F0570',
      'icon-bullet-list'     => '\F05C7',
      'icon-archive'         => '\F003C',
      'icon-adressbook'      => '\F00BF',
      'icon-false'           => '\F0156',
      'icon-cancel'          => '\F073A',
      'icon-edit'            => '\F03EB',
      'icon-error'           => '\F0028',
      'icon-workflow'        => '\F01D0',
      'icon-move'            => '\F044E',
      'icon-move-left'       => '\F054C',
      'icon-server'          => '\F048B',
      'icon-package'         => '\F03D3',
      'icon-home'            => '\F02DC',
      'icon-help'            => '\F02D6',
      'icon-youtube'         => '\F05C3',
      'icon-dropbox'         => '\F01E3',
      'icon-aws'             => '\F0E0F',
      'icon-cloud'           => '\F015F',
      'icon-googledrive'     => '\F02B6',
      # 'icon-time'            => '\F0020',
      'icon-stats'           => '\F041F',
      'icon-chart'           => '\F0128',
      'icon-warning'         => '\F0026',
      'icon-fullscreen'      => '\F0293',
      'icon-fullscreen-exit' => '\F0294',
      'icon-fav-off'         => '\F02D5',
      'icon-star-o'          => '\F04D2',
      'icon-checked'         => '\F012C',
      # 'icon-true' => '\F012C',
      'icon-notice'         => '\F05D6',
      'icon-checked-circle' => '\F05E0',
      'icon-report'         => '\F0219',
      'icon-comment'        => '\F017A',
      'icon-comments'       => '\F0368',
      'icon-summary'        => '\F0219',
      'icon-lightning'      => '\F0241',
      'icon-eye'            => '\F0208',
      # 'icon-watcher' => '\F0208',
      # 'icon-watch' => '\F0208',
      'icon-relation'     => '\F0337',
      'icon-integrate'    => '\F00F8',
      'icon-tracker'      => '\F014D',
      'icon-issue-status' => '\F014E',
      'icon-stack'        => '\F0240',
      'icon-help-bubble'  => '\F078B',
      'icon-money'        => '\F1176',
      'icon-euro'         => '\F01AD',
      'icon-calculation'  => '\F00EC',
      # 'icon-calculator' => '\F00EC',
      'icon-export'        => '\F0207',
      'icon-import'        => '\F02FA',
      'icon-calendar-year' => '\F0679',
      # 'icon-calendar-quarter' => '\F0679',
      # 'icon-calendar-month' => '\F0679',
      # 'icon-calendar-week' => '\F0679',
      # 'icon-calendar-day' => '\F0679',
      'icon-linux'        => '\F033D',
      'icon-link'         => '\F0337',
      'icon-unlink'       => '\F0338',
      'icon-arrow'        => '\F0142',
      'icon-back'         => '\F0141',
      'icon-arrow-alt'    => '\F035F',
      'icon-toggler-left' => '\F035E',
      # 'icon-back-alt' => '\F054C',
      'icon-toggler' => '\F0417',
      # 'icon-new-template' => '\F0417',
      'icon-add'                => '\F0416',
      'icon-add-action'         => '\F0415',
      'icon-classic-arrow'      => '\F0055',
      'icon-classic-arrow-left' => '\F004E',
      'icon-undo'               => '\F054C',
      'icon-redo'               => '\F044E',
      # 'icon-arrow-left' => '\F0141',
      # 'icon-keyboard-arrow-left' => '\F0141',
      # 'icon-keyboard-arrow-right' => '\F0142',
      'icon-first_page' => '\F0600',
      'icon-last_page'  => '\F0601',
      'icon-close'      => '\F0156',
      'icon-bulb'       => '\F0336',
      'icon-settings'   => '\F08BB',
      'icon-filter'     => '\F0232',
      'icon-play'       => '\F040A',
      'icon-pause'      => '\F03E4',
      'icon-txt'        => '\F0219',
      'icon-print'      => '\F042A',
      'icon-atom'       => '\F0768',
      'icon-csv'        => '\F0C7E',
      # 'icon-xls' => '\F021B',
      # 'icon-xlsx' => '\F021B',
      # 'icon-pdf' => '\F0225',
      # 'icon-html' => '\F022E',
      # 'icon-project' => '\F0645',
      # 'icon-projects' => '\F0645',
      'icon-folder'       => '\F024B',
      'icon-new-document' => '\F0752',
      # 'icon-file' => '\F0214',
      'icon-copy'      => '\F018F',
      'icon-duplicate' => '\F0191',
      'icon-issue'     => '\F014D',
      'icon-page'      => '\F09EE',
      'icon-save'      => '\F0193',
      # 'icon-save-issue' => '\F0193',
      # 'icon-download' => '\F01DA',
      'icon-downloads'             => '\F09E9',
      'icon-key'                   => '\F0306',
      'icon-server-authentication' => '\F0469',
      'icon-roles'                 => '\F088F',
      'icon-calendar'              => '\F00ED',
      'icon-ics'                   => '\F00F5',
      # 'icon-db-key' => '\F0306',
      # 'icon-cf' => '\F0416',
      'icon-cross-move' => '\F01BE',
      'icon-star'       => '\F04CE',
      'icon-fav'        => '\F02D1',
      'icon-globe'      => '\F01E7',
      'icon-reorder'    => '\F0688',
      'icon-message'    => '\F0361',
      # 'icon-mail' => '\F01EE',
      # 'icon-email' => '\F01EE',
      'icon-email-add'      => '\F09EB',
      'icon-mute'           => '\F057E',
      'icon-unmute'         => '\F075F',
      'icon-apple'          => '\F0035',
      'icon-android'        => '\F0032',
      'icon-windows'        => '\F05B3',
      'icon-basecamp'       => '\F0EDD',
      'icon-power'          => '\F0425',
      'icon-person-euro'    => '\F0584',
      'icon-cash-desk'      => '\F0CF4',
      'icon-person-add'     => '\F0014',
      'icon-snowflake'      => '\F0717',
      'icon-christmas-tree' => '\F0405',
      'icon-christmas-ball' => '\F0A8C',
      'icon-present'        => '\F0E44',
      # 'icon-christmas-linux' => '\F33D',
      'icon-scrum' => '\F046E',
      # 'icon-agile' => '\F046E',
      # 'icon-kanban' => '\F046E',
      # 'icon-ms-project' => '\F214',
      'icon-heart-o' => '\F02D5',
      'icon-heart'   => '\F02D1',
      'icon-loading' => '\F0772',
      # 'icon-easy' => '\00ea',
      # 'icon-logo' => '\00ea',
      'icon-cake1'    => '\F00EA',
      'icon-cake2'    => '\F00EB',
      'icon-cake3'    => '\F00E9',
      # 'icon-falcon'   => '\F08D8',
      'icon-vcard'    => '\F05D2',
      'icon-brick'    => '\F07FE',
      'icon-calc'     => '\F00EC',
      'icon-calc2'    => '\F0A9A',
      'icon-controls' => '\F066A',
      'icon-file-new' => '\F0752',
      'icon-drop-o'   => '\F058C',
      # 'icon-drop' => '\F058C',
      'icon-drop-half'  => '\F05CC',
      'icon-drop-empty' => '\F058D',
      # 'icon-zip'        => '\F05C4',
      # 'icon-brick-2' => '\F07FE',
      'icon-popup'     => '\F0137',
      'icon-biohazard' => '\F00A7',
      'icon-radiation' => '\F043C',
      'icon-skull'     => '\F068C',
      'icon-people'    => '\F0148',
      'icon-target-1'  => '\F05DD',
      'icon-target-2'  => '\F08C9',
      'icon-icq'       => '\F0365',
      'icon-bookmark'  => '\F00C0',
      'icon-rubl'      => '\F01B1',
      # 'icon-baht' => '\00e6',
      'icon-invoice'     => '\F0449',
      'icon-refresh'     => '\F0450',
      'icon-crm-1'       => '\F0CF0',
      'icon-user-folder' => '\F04FE',
      'icon-user-target' => '\F0BD0',
      # 'icon-calculation-2' => '\F00EC',
      'icon-thumb'   => '\F0513',
      'icon-like'    => '\F0514',
      'icon-thumb-0' => '\F0511',
      'icon-unlike'  => '\F0512',
      # 'icon-thumb-1' => '\F0513',
      'icon-thumb-2'    => '\F0515',
      'icon-award'      => '\F053B',
      'icon-award-1'    => '\F053C',
      'icon-binoculars' => '\F00A5',
      'icon-search'     => '\F0349',
      'icon-location'   => '\F034E',
      # 'icon-tree' => '\F0645',
      # 'icon-hierarchy' => '\F0645',
      # 'icon-file-xls' => '\F021B',
      'icon-file-oo'    => '\F0214',
      'icon-file-doc'   => '\F022C',
      'icon-file-point' => '\F0227',
      'icon-file-adobe' => '\F0225',
      'icon-file-blank' => '\F0224',
      'icon-file-css'   => '\F022E',
      'icon-file-xml'   => '\F022E',
      'icon-file-zip'   => '\F05C4',
      'icon-puzzle'     => '\F0431',
      'icon-recycle'    => '\F044C',
      'icon-attachment' => '\F0066',
      'icon-qr'         => '\F0432',
      # 'icon-qr-code' => '\F0432',
      'icon-table' => '\F04F1',
      # 'icon-butterfly' => '\F02D6',
      'icon-ruby'           => '\F0D2D',
      'icon-barcode'        => '\F0071',
      'icon-flashlight-on'  => '\F0244',
      'icon-flashlight-off' => '\F0245',
      # 'icon-flashlight-disabled' => '\F0245',
      'icon-disc'    => '\F05EE',
      # 'icon-wf-none' => '\F012C',
      # 'icon-wf-waiting' => '\F214',
      # 'icon-wf-assigned' => '\F214',
      'icon-more-vert'       => '\F01D9',
      'icon-more-horiz'      => '\F01D8',
      'icon-legend'          => '\F0571',
      'icon-icon'            => '\F01F5',
      'icon-side'            => '\F00BD',
      'icon-collapse'        => '\F0375',
      'icon-expand'          => '\F0416',
      'icon-cut'             => '\F0190',
      'icon-paste'           => '\F0192',
      'icon-expand-more'     => '\F0140',
      'icon-expand-less'     => '\F0143',
      'icon-facebook-box'    => '\F020C',
      'icon-linkedin-box'    => '\F033B',
      'icon-twitter-box'     => '\F0544',
      'icon-google-plus-box' => '\F02BD',
      'icon-info'            => '\F02FC',
      'icon-phone'           => '\F03F2',
  }

  def easy_icon_name_to_char(name)
    EASY_ICONS[name]
  end

  def easy_icon_char_to_name(char)
    EASY_ICONS.key(char)
  end

  def easy_icon_select_tag(name, selected = nil, options = {})
    icons          = EasyIconsHelper::EASY_ICONS
    select_options = icons.map { |i| { :label => (i[1].gsub(/\\(.*)/, '&#x\1').html_safe), :id => i[0] } }
    selected       = { :name => select_options.detect { |o| o[:id] == selected }.try(:[], :label) || '', :id => selected }
    id             = name.to_s.tr('[', '_').delete(']')

    icon_tag = ''
    icon_tag << label_tag(id, options[:label]) if options[:label]
    icon_tag << easy_autocomplete_tag(name, selected, select_options, { :html_options => { :id => id, :class => 'easy-icon-select' },
                                                                        :render_item  => '
                  function (ul, item) {
                    return $("<li class=\'easy-icon-select\'>")
                    .data("item.autocomplete", item)
                    .html(item.label)
                    .appendTo(ul);
                  }',
                                                                        :onchange     => 'if(ui.item){$(event.target).val($("<div>").html(ui.item.value).text())};'
    })
    icon_tag.html_safe
  end

end
