gem 'activemodel-serializers-xml'
gem 'activerecord-import', '>= 0.4.0'
gem 'activeresource'
gem 'acts-as-taggable-on', '~> 6.0.0'
gem 'awesome_nested_set'

gem 'cocoon'
gem 'countries'

gem 'geocoder', require: false

gem 'httparty'
gem 'icalendar', '2.5.3'
gem 'letter_avatar'
gem 'loofah-activerecord'
gem 'loofah', '~> 2.7.0'
if @dependencies.reject! { |d| d.name == 'mail' }
  gem 'mail'
end
# https://www.redmine.org/issues/33768
if @dependencies.reject! { |d| d.name == 'csv' }
  gem 'csv', (RUBY_VERSION < '2.5' ? ['>= 3.1.1', '<= 3.1.5'] : '~> 3.1.1')
end
gem 'nitlink', require: false

gem 'omniauth', '>= 1.4.2'
gem 'omniauth-oauth2', '~>1.5.0'
gem 'oj', (RUBY_VERSION < '2.4' ? '3.10.8' : '~> 3.10.16'), platforms: [:mri, :mingw, :x64_mingw]

gem 'paperclip', '~> 6.0.0'
gem 'password_strength', '~> 1.1.4'
@dependencies.reject! { |d| d.name == 'puma' }
gem 'puma', '> 4', '< 6'
gem 'nio4r', '2.5.2' if RUBY_VERSION < '2.4'
gem 'faraday', '<= 1.0.1' if RUBY_VERSION < '2.4'
gem 'omniauth-saml', '1.10.1' if RUBY_VERSION < '2.4'
gem 'css_parser', '1.7.1' if RUBY_VERSION < '2.4'
gem 'parallel', '1.19.2' if RUBY_VERSION < '2.5'

gem 'rack', '~> 2.2.2'
gem 'rails-observers'
gem 'redis'
gem 'redis-namespace', (RUBY_VERSION < "2.4" ? "~> 1.6.0" : "~> 1.7.0")
gem 'redmine-installer', '>= 2.1', require: false
gem 'redmine_extensions', '~> 0.3.11'
gem 'rinku', platforms: [:mri, :mingw, :x64_mingw]
gem 'roo', require: false
gem 'roo-xls', require: false
gem 'rqrcode', '~> 1.0.0'
gem 'ruby-msg', '~> 1.5.2'
gem 'rubyXL', '~> 3.4.14'
gem 'rubyzip', (RUBY_VERSION < '2.4') ? '~> 1.3.0' : '~> 2.2.0'

gem 'sassc-rails', platforms: [:mri, :mingw, :x64_mingw]
gem 'sassc', '>= 1.12.1'
# Sidekiq ~>6.0 requires Redis 4.0 which is not in Debian 9.11
gem 'sidekiq', '~> 5.2', '>= 5.2.7'
gem 'sidekiq-cron'
# gem 'sucker_punch', '~> 2.0'
gem 'simple-rss'
if @dependencies.reject! { |d| d.name == 'simplecov' }
  gem 'simplecov', '~> 0.16.1', require: false
end

@dependencies.reject! { |d| d.name == 'sprockets' }
gem "sprockets", "~> 3.7.2"
gem 'sprockets-rails', '>= 3.0.0'

gem 'uglifier', '4.1.12'

gem 'vcard'
gem 'parslet'
gem "easy_server_timing", '~> 0.1'

group :development, :test do
  gem 'bootsnap', require: false
end

group :js_runtime do
  gem 'therubyracer', require: false, platforms: :mri
end

group :test do
  gem 'rspec-retry', '~> 0.5.7'
  gem 'rails-controller-testing'

  if @dependencies.reject! { |d| d.name == 'selenium-webdriver' }
    gem "selenium-webdriver", "3.142.6"
  end
  if @dependencies.reject! { |d| d.name == 'capybara' }
    gem "capybara", (RUBY_VERSION < "2.4" ? '3.15' : '3.29')
  end
end

Dir.glob File.expand_path("../easy_helpers/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
  eval_gemfile file
end

Dir.glob File.expand_path("../easy_plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
  eval_gemfile file
end
